# Generated by Django 2.2.24 on 2023-02-06 13:41

from django.db import migrations, models
import iberian.utils.model_util


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='generic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('iso', models.CharField(blank=True, max_length=3, null=True)),
            ],
            bases=(models.Model, iberian.utils.model_util.info),
        ),
    ]
