# Generated by Django 2.2.24 on 2023-02-06 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import partial_date.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliography',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_title', models.CharField(default='', max_length=250)),
                ('author', models.CharField(blank=True, max_length=50, null=True)),
                ('year', partial_date.fields.PartialDateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Church',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('date_lower', partial_date.fields.PartialDateField(blank=True, null=True)),
                ('date_upper', partial_date.fields.PartialDateField(blank=True, null=True)),
                ('coordinates_latitude', models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=8, null=True)),
                ('coordinates_longitude', models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=8, null=True)),
                ('textual_evidence', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1, null=True)),
                ('material_evidence', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.BooleanField(default=False, help_text='Complete', verbose_name='Completed')),
                ('bibliography', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='saints.Bibliography')),
                ('bibliography_many', models.ManyToManyField(blank=True, default='', related_name='bibliographies', to='saints.Bibliography')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=5, default=0, max_digits=7)),
                ('longitude', models.DecimalField(decimal_places=5, default=0, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Feast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(default='', max_length=100)),
                ('date_lower', partial_date.fields.PartialDateField(blank=True, null=True)),
                ('date_upper', partial_date.fields.PartialDateField(blank=True, null=True)),
                ('text', models.TextField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('status', models.BooleanField(default=False, help_text='Complete', verbose_name='Completed')),
                ('bibliography', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='saints.Bibliography')),
                ('bibliography_many', models.ManyToManyField(blank=True, default='', related_name='bibliographies_inscription', to='saints.Bibliography')),
                ('current_location', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='saints.Church')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LiturgicalManuscript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf_no', models.CharField(default='', max_length=100)),
                ('date_lower', partial_date.fields.PartialDateField(blank=True, null=True)),
                ('date_upper', partial_date.fields.PartialDateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('status', models.BooleanField(default=False, help_text='Complete', verbose_name='Completed')),
                ('bibliography', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='saints.Bibliography')),
                ('bibliography_many', models.ManyToManyField(blank=True, default='', related_name='bibliographies_litman', to='saints.Bibliography')),
                ('feast', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='saints.Feast')),
                ('original_location', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originallocationslitman', to='saints.Church')),
                ('original_location_city', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='saints.City')),
            ],
        ),
        migrations.CreateModel(
            name='ManuscriptType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saints.City')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=256)),
                ('date_lower', partial_date.fields.PartialDateField(blank=True, null=True)),
                ('date_upper', partial_date.fields.PartialDateField(blank=True, null=True)),
                ('textual_evidence', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1, null=True)),
                ('material_evidence', models.CharField(blank=True, choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=1, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('status', models.BooleanField(default=False, help_text='Complete', verbose_name='Completed')),
                ('bibliography', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='saints.Bibliography')),
                ('bibliography_many', models.ManyToManyField(blank=True, default='', related_name='bibliographies_object', to='saints.Bibliography')),
                ('current_location', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='saints.Church')),
                ('current_location_museum', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='saints.Museum')),
                ('original_location', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='originallocations', to='saints.Church')),
                ('original_location_city', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='saints.City')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Saint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('feast_day', models.CharField(blank=True, max_length=256, null=True)),
                ('feast_day_old', partial_date.fields.PartialDateField(blank=True, null=True)),
                ('death_date', partial_date.fields.PartialDateField(blank=True, null=True)),
                ('death_place', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('status', models.BooleanField(default=False, help_text='Complete', verbose_name='Completed')),
            ],
        ),
        migrations.CreateModel(
            name='SaintType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaintObjectRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='saints.Object')),
                ('saint', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='saints.Saint')),
            ],
        ),
        migrations.CreateModel(
            name='SaintLitManuscriptRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liturgical_manuscript', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='saints.LiturgicalManuscript')),
                ('saint', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='saints.Saint')),
            ],
        ),
        migrations.CreateModel(
            name='SaintLinkRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, default='', max_length=256)),
                ('saint', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='saints.Saint')),
            ],
        ),
        migrations.CreateModel(
            name='SaintInscriptionRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscription', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='saints.Inscription')),
                ('saint', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='saints.Saint')),
            ],
        ),
        migrations.CreateModel(
            name='SaintChurchRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='saints.Church')),
                ('saint', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='saints.Saint')),
            ],
        ),
        migrations.AddField(
            model_name='saint',
            name='type',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saints', to='saints.SaintType'),
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_number', models.PositiveIntegerField(blank=True, null=True)),
                ('extent_shapefile', models.FileField(blank=True, max_length=50, null=True, upload_to='shapefiles/')),
                ('city', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='saints.City')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectLinkRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, default='', max_length=256)),
                ('object', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='saints.Object')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectChurchRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', partial_date.fields.PartialDateField(blank=True, null=True)),
                ('end_date', partial_date.fields.PartialDateField(blank=True, null=True)),
                ('church', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='saints.Church')),
                ('object', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='saints.Object')),
            ],
        ),
        migrations.AddField(
            model_name='object',
            name='original_location_region',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='saints.Region'),
        ),
        migrations.AddField(
            model_name='object',
            name='type',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='saints.ObjectType'),
        ),
        migrations.AddField(
            model_name='liturgicalmanuscript',
            name='original_location_region',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='saints.Region'),
        ),
        migrations.AddField(
            model_name='liturgicalmanuscript',
            name='provenance',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='saints.Church'),
        ),
        migrations.AddField(
            model_name='liturgicalmanuscript',
            name='provenance_museum',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='saints.Museum'),
        ),
        migrations.AddField(
            model_name='liturgicalmanuscript',
            name='rite',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='saints.Rite'),
        ),
        migrations.AddField(
            model_name='liturgicalmanuscript',
            name='type',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='saints.ManuscriptType'),
        ),
        migrations.CreateModel(
            name='LitManuscriptLinkRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, default='', max_length=256)),
                ('liturgical_manuscript', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='saints.LiturgicalManuscript')),
            ],
        ),
        migrations.CreateModel(
            name='LitManuscriptChurchRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', partial_date.fields.PartialDateField(blank=True, null=True)),
                ('end_date', partial_date.fields.PartialDateField(blank=True, null=True)),
                ('church', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='saints.Church')),
                ('liturgical_manuscript', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='saints.LiturgicalManuscript')),
            ],
        ),
        migrations.CreateModel(
            name='InscriptionLinkRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, default='', max_length=256)),
                ('inscription', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='saints.Inscription')),
            ],
        ),
        migrations.CreateModel(
            name='InscriptionChurchRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', partial_date.fields.PartialDateField(blank=True, null=True)),
                ('end_date', partial_date.fields.PartialDateField(blank=True, null=True)),
                ('church', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='saints.Church')),
                ('inscription', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='saints.Inscription')),
            ],
        ),
        migrations.AddField(
            model_name='inscription',
            name='current_location_museum',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='saints.Museum'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='original_location',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originallocationsinscription', to='saints.Church'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='original_location_city',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='saints.City'),
        ),
        migrations.AddField(
            model_name='inscription',
            name='original_location_region',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='saints.Region'),
        ),
        migrations.CreateModel(
            name='ChurchLinkRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(blank=True, default='', max_length=256)),
                ('church', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='saints.Church')),
            ],
        ),
        migrations.AddField(
            model_name='church',
            name='city',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='saints.City'),
        ),
        migrations.AddField(
            model_name='church',
            name='institution_type',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='saints.InstitutionType'),
        ),
        migrations.AddField(
            model_name='church',
            name='region',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='saints.Region'),
        ),
    ]
